services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-docky
    restart: always
    ports:
      - "8086:8080"
      - "50000:50000"
    volumes:
      - "${JENKINS_HOME}:/var/jenkins_home"